### ISSUE TITLE
run-command failure because of license issue

### ISSUE THREAD

**Issue by kikd** [matlab-actions/run-command#17]
Hello.
Thank you for providing very awesome action template!

I'm using this actions for scheduled processing in [my repository](/kikd/covid19-nagano-analyze), but that process failing since 19:00 GMT because of license issue.

<details>
<summary>Error log (click to expand)</summary>

```
Mon, 20 Sep 2021 19:10:51 GMT Run matlab-actions/run-command@v1
Mon, 20 Sep 2021 19:10:51 GMT   with:
Mon, 20 Sep 2021 19:10:51 GMT     command: addpath("scripts"), datawrangle;
Mon, 20 Sep 2021 19:10:51 GMT   env:
Mon, 20 Sep 2021 19:10:51 GMT     TZ: Asia/Tokyo
Mon, 20 Sep 2021 19:10:51 GMT Generate script
Mon, 20 Sep 2021 19:10:51 GMT   Successfully generated script
Mon, 20 Sep 2021 19:10:51 GMT Run command
Mon, 20 Sep 2021 19:10:51 GMT   /home/runner/work/_actions/matlab-actions/run-command/v1/dist/bin/run_matlab_command.sh cd('/tmp/run_matlab_command-7nAuGY'); command_ac342a1f_743f_4345_af9a_77549079f3d2
Mon, 20 Sep 2021 19:11:11 GMT   ======BEGIN LICENSE MANAGER ERROR======
Mon, 20 Sep 2021 19:11:11 GMT   License checkout failed.
Mon, 20 Sep 2021 19:11:11 GMT   License Manager Error 4402
Mon, 20 Sep 2021 19:11:11 GMT   SSL Exception: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
Mon, 20 Sep 2021 19:11:11 GMT   
Mon, 20 Sep 2021 19:11:11 GMT   Troubleshoot this issue by visiting: 
Mon, 20 Sep 2021 19:11:11 GMT   https://www.mathworks.com/support/lme/R2021a/4402
Mon, 20 Sep 2021 19:11:11 GMT   
Mon, 20 Sep 2021 19:11:11 GMT   Diagnostic Information:
Mon, 20 Sep 2021 19:11:11 GMT   Feature: MATLAB_Distrib_Comp_Engine 
Mon, 20 Sep 2021 19:11:11 GMT   License path:  
Mon, 20 Sep 2021 19:11:11 GMT   Licensing error: 4402,0.======END LICENSE MANAGER ERROR======
Mon, 20 Sep 2021 19:11:11 GMT   
Mon, 20 Sep 2021 19:11:11 GMT Error: Error: The process '/home/runner/work/_actions/matlab-actions/run-command/v1/dist/bin/run_matlab_command.sh' failed with exit code 1
```
</details>

Before that completed successfully without specify any license information.

What is happening in license management? 
I would appreciate if you could help.

**Comment by acampbel** [comment]
Thank you for creating this issue. This is due to an Online Licensing partial outage that is currently under investigation. Our apologies for the inconvenience, but we will resolve it as soon as possible. You should not have to do anything, these actions are free for public repositories such as yours. Please check our status page for up to date details. 

https://status.mathworks.com/

Thank you for reporting this issue. We hope to resolve it quickly.

**Comment by kikd** [comment]
Thank you for answering. 
I didn't know that status page. It very useful.

I'll close this and waiting for resolve outage.
Regards.

**Comment by acampbel** [comment]
> Thank you for answering.
> I didn't know that status page. It very useful.
> 
> I'll close this and waiting for resolve outage.
> Regards.

@kikd The Online Licensing service should be available and running now. Thank you for your patience.
