### ISSUE TITLE
Random crashes of `run-command` on Ubuntu Linux hosts.

### ISSUE THREAD

**Issue by bcoconni** [matlab-actions/run-command#27]
We are having random crashes of `matlab-actions/run-command` on Ubuntu Linux hosts where the action reports an error about a failed assertion `listp != NULL` (see the error messages below)

![image](https://user-images.githubusercontent.com/7502904/189478797-f71191a7-a530-40e5-ab7f-a37ef53118d6.png)

This is generally resolved by [re-running the workflow as instructed by GitHub docs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow) until the job succeeds but still it's annoying to have these random crashes.

Any idea about what might cause this failure ?

Thanks.

**Comment by mcafaro** [comment]
This looks similar to a known issue with MATLAB and glibc: https://www.mathworks.com/matlabcentral/answers/1454674-why-does-matlab-crash-on-linux-with-inconsistency-detected-by-ld-so-elf-dl-tls-c-597-_dl_allo

You can either patch glibc as described in [these instructions](https://github.com/mathworks/build-glibc-bz-19329-patch) or use Ubuntu 22.04 where glibc has already been patched.

**Comment by bcoconni** [comment]
Thanks for the prompt answer and the tip @mcafaro.
I'll try that and let you know if that solves the problem.

**Comment by bcoconni** [comment]
Indeed since the workflow has been switched to Ubuntu 22.04, crashes are no longer occurring.
Thanks @mcafaro.
