### ISSUE TITLE
Getting security alerts while using this action for enterprise project

### ISSUE THREAD

**Issue by manoj27730** [matlab-actions/run-command#31]
Hi Team,

  I need this actions to be used by my project and since it's not allowed by default our enterprise GitHub Team need to review and add it for our project. Our GitHub Team has found alert and mentioned below point.

**"The actions requested are available on our github instance but we are seeing dependabot alerts. Since those repo have vulnerabilities, we won’t be able to make it public.  Look like it’s patched on the master but they haven’t release it.  Please file issue with the actions owner to release patched version. After that, we can make it available for your team to use."**

Can you please look into it and help.

**Comment by manoj27730** [comment]
<img width="532" alt="Alert" src="https://user-images.githubusercontent.com/24359931/199657198-e5fa5c87-8770-4c4c-ae93-2fdb6b957d24.PNG">

**Comment by davidbuzinski** [comment]
Hi @manoj27730 thanks for bringing this to our attention. We have bumped the mentioned dependencies in the new release v1.1.2.

Thanks,
David

**Comment by manoj27730** [comment]
<img width="664" alt="error" src="https://user-images.githubusercontent.com/24359931/201596340-ad45aa25-3e1b-460d-9bac-77f415496128.PNG">

Hi David,

  I am using the latest version of this action in my code but still getting error. Can you please suggest what needs to be done?

**Comment by manoj27730** [comment]
The above issue is fixed. I changed the repository name "matlab-actions" with our private repository name and it worked.
