### ISSUE TITLE
Update to node.js 20

### ISSUE THREAD

**Issue by nicoH2FLY** [matlab-actions/run-command#49]
Got the following warning from github:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: matlab-actions/run-command@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by davidbuzinski** [comment]
Hi @nicoH2FLY,

We have released a new v2 release for all of our MATLAB Actions. The v2 release is updated to use Node.js 20. This applies to all of our actions including `setup-matlab`, `run-command`, `run-tests`, and `run-build`.

Thanks,
David

**Comment by nicoH2FLY** [comment]
Thank you very much!
