### ISSUE TITLE
Tests failing on Github and passing locally

### ISSUE THREAD

**Issue by pollaro** [matlab-actions/run-command#64]
I'm running some unittests on my data. They repeatedly pass on my local system, but they fail on github actions.

![Failing on github](https://github.com/user-attachments/assets/d964ec50-e94d-4419-9550-405cc464efa9)

![Passing on my computer](https://github.com/user-attachments/assets/b3024b40-0bd9-4539-a4dd-aa5293fe65bf)

**Comment by pollaro** [comment]
Hello, @mcafaro @acampbel, can someone take a look at this? My unittests fail here but are all passing locally

**Comment by mcafaro** [comment]
Hi @pollaro,

That looks like a legitimate test failure. There is nothing in `run-command` that would cause a particular failure like that. Perhaps there is something in the code that is platform-specific (running Linux on GitHub Actions and in Windows locally)? Or release-specific (running the same release of MATLAB both places)? Or perhaps there are interactions between test points (locally I only see permutationEdgeTest being run in isolation, but on GitHub Actions it looks like all tests are being run)?

Best,
Mark

**Comment by pollaro** [comment]
@mcafaro Yeah, it's a test failure, that's the problem. 
When I run them on my work computer, yes it's Linux, they all pass. We're using Matlab2020, which actions doesn't have. Has the math changed that much?
