### ISSUE TITLE
Clarify terms of use

### ISSUE THREAD

**Issue by dweindl** [matlab-actions/run-command#9]
This action looks pretty useful. Unfortunately, the terms of use are not very clear to me.

The README states:

> When you use the Run MATLAB Command action, you execute third-party code that is licensed under separate terms.

Where can I find the terms for using Matlab via this action?

**Comment by jwpereira** [comment]
Thanks for your question, @dweindl! 😄 

I understand you are asking about the terms for using MATLAB via the `run-command` action.

The line you highlighted particularly speaks about the third-party libraries (such as those provided by GitHub) we’re leveraging under the hood to make this action possible.

As for MATLAB itself, this action passes the command you specify to the MATLAB installation on the running agent. As a result:

- If you are using a self-hosted agent, the terms for using MATLAB are included within the MATLAB installation itself (`matlabroot`). 
- If you are using a GitHub-Hosted agent and a MATLAB installation provided via the [setup-matlab](https://github.com/matlab-actions/setup-matlab) action, you can refer to the following license: https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/license.txt 

Please let me know if you have any further questions! 😄

**Comment by dweindl** [comment]
Thanks for the quick reply, @jwpereira.

> If you are using a GitHub-Hosted agent and a MATLAB installation provided via the [setup-matlab](https://github.com/matlab-actions/setup-matlab) action, you can refer to the following license: https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/license.txt

This answers my question, thanks. It might be helpful for others to include this reference somewhere in the README here or with `setup-matlab`. (Sorry if it is already and I just overlooked it.) Otherwise this issue can be closed.

**Comment by jwpereira** [comment]
Glad I could help 😄
And thank you for your feedback too! 😁
